# Generated by Django 5.2.7 on 2025-10-07 15:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Serial number must be 6 digits.')])),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('borrowed_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='readers.reader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
